name: my_widget_book
description: "lego is all you need"
#publish_to: 'none'
#repository: https://github.com/melodysdreamj/lego

version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  auto_size_text:
  bot_toast:
  device_preview_minus: ^1.0.6
  flutter:
    sdk: flutter
  flutter_color:
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  infinite_listview:
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  styled_widget:
  tuple: ^2.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  hello_world_page_lego:
  screenutil_lego:
  bot_toast_lego:
  toss_intro_page_lego:
  insta_personal_page_lego:
  widget_binding_lego:
  netflix_main_view_lego:
  facebook_main_view_lego:

flutter:
  uses-material-design: true
  assets:
    - assets/lego/facebook_main_view_lego/
    - assets/lego/netflix_main_view_lego/
    - assets/lego/insta_personal_page_lego/
    - assets/lego/toss_intro_page_lego/
    - assets/pubdev.svg
    - assets/github.svg